blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("",views.blog_list,name='bloglist'),
    path("<int:id>",views.blog_detail,name='blogdetail'),
    path("tags/<slug:tag>",views.blog_tags,name='tags'),
    path("categories/<slug:category>",views.blog_categories,name='categories'),
    path("search/",views.search,name='search'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls',namespace='pages')),
    path('foods/',include('foods.urls',namespace='foods')),
    path('reservation/',include('reservation.urls',namespace='reservation')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('gallery/',include('gallery.urls',namespace='gallery')),
    path('cantact/',include('cantact.urls',namespace='cantact')),
]

blog/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    published = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title 


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    published = models.DateTimeField(auto_now=False, auto_now_add=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title 

class Blog(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    content = RichTextField()
    created = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/%Y/%m/%d')
    category = models.ForeignKey(Category,related_name='blog',on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag,related_name='blogs')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Article"

class Comments(models.Model):
    blog = models.ForeignKey(Blog,related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    message = models.TextField()
    date = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
            return self.name

blog/forms.py
from .models import Comments
from django import forms

class CommentsForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=50)
    message = forms.CharField(widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Blog, Category, Tag, Comments
from .forms import CommentsForm
from django.core.paginator import Paginator

def blog_list(request):
    blogs = get_list_or_404(Blog)
    paginator = Paginator(blogs,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "blogs":page_obj
    }
    return render(request,"blog/blog.html",context)

def blog_detail(request,id):
    blog = get_object_or_404(Blog,id=id)
    tags = Tag.objects.all().filter(blogs=blog)
    recents = Blog.objects.all().order_by("-created")[:3]
    categories = Category.objects.all()
    comments = Comments.objects.all().filter(blog=blog)

    if request.method == 'POST':
        comments_form = CommentsForm(request.POST)
        if comments_form.is_valid():
            new_name = comments_form.cleaned_data['name']
            new_email = comments_form.cleaned_data['email']
            new_message = comments_form.cleaned_data['message']
            new_comment = Comments(blog=blog,name=new_name,email=new_email,message=new_message)
            new_comment.save()

    context = {
        "blog":blog ,
        "tags":tags ,
        "recents":recents ,
        "categories":categories ,
        "comments":comments ,
    }
    return render(request,'blog/blog-details.html',context)


def blog_tags(request,tag):
    blogs = Blog.objects.filter(tag__slug=tag)
    context = {
        "blogs":blogs
    }
    return render(request,"blog/blog.html",context)

def blog_categories(request,category):
    blogs = Blog.objects.filter(category__slug=category)
    context = {
        "blogs":blogs
    }
    return render(request,"blog/blog.html",context)

def search(request):
    if request.method == 'GET':
        q = request.GET.get('search')
    blog_list = Blog.objects.filter(title__icontains=q)
    if blog_list.count() == 0:
        blog_list = Blog.objects.filter(content__icontains=q)
    return render(request,"blog/blog.html",{"blogs":blog_list})

templates/blog/blog-details.html
{% extends 'base.html' %}
{% block blog-active %}active{% endblock blog-active %}
{% load static %}
{% block content %}
	
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog details -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>{{blog.title}}</h2>
						<p>{{blog.description}}</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-12">
					<div class="blog-inner-details-page">
						<div class="blog-inner-box">
							<div class="side-blog-img">
								<img class="img-fluid" src="{{blog.image.url}}" alt="">							
								<div class="date-blog-up">
									{{blog.created|date:"b d"}}
								</div>
							</div>
							<div class="inner-blog-detail details-page">
								<h3>{{blog.description}}</h3>
								<ul>
									<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author.first_name}} {{blog.author.last_name}}</span></li>
									<li>|</li>
									<li><i class="zmdi zmdi-time"></i>Time : <span>{{blog.created|time}}</span></li>
								</ul>
								<p>{{blog.content|safe}}</p>
							</div>
						</div>
						<div class="blog-comment-box">
							<h3>Comments</h3>
							{% for comment in comments %}
							<div class="comment-item">
								<div class="comment-item-left">
									<img src="{% static 'images/avt-img.jpg' %}" alt="">
								</div>
								<div class="comment-item-right">
									<div class="pull-left">
										<a href="#">{{comment.name}}</a>
									</div>
									<div class="pull-right">
										<i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{comment.date|date:"Y b d"}}</span>
									</div>
									<div class="des-l">
										<p>{{comment.message}}</p>
									</div>
									<a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
								</div>
							</div>
							<br>
							{% endfor %}
							{% comment %} <div class="comment-item children">
								<div class="comment-item-left">
									<img src="{% static 'images/avt-img.jpg' %}" alt="">
								</div>
								<div class="comment-item-right">
									<div class="pull-left">
										<a href="#">Admin</a>
									</div>
									<div class="pull-right">
										<i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>1.30 pm</span>
									</div>
									<div class="des-l">
										<p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>
									</div>
									<a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
								</div>
							</div> {% endcomment %}
						</div>
						<div class="comment-respond-box">
							<h3>Leave your comment </h3>
							<div class="comment-respond-form">
								<form id="commentrespondform" class="comment-form-respond row" method="post">
									{% csrf_token %}
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
											<input id="name_com" class="form-control" name="name" placeholder="Name" type="text">
										</div>
										<div class="form-group">
											<input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
											<textarea class="form-control" id="textarea_com" name="message" placeholder="Your Message" rows="2"></textarea>
										</div>
									</div>
									<div class="col-lg-12 col-md-12 col-sm-12">
										<button class="btn btn-submit">Submit comment</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			
				<div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
					<div class="right-side-blog">
						<h3>Search</h3>
						<form method="GET" action="{% url 'blog:search' %}">
						<div class="blog-search-form">
							<input name="search" placeholder="Search blog" type="text">
							<button class="search-btn" type="submit">
								<i class="fa fa-search" aria-hidden="true"></i>
							</button>
						</div>
					</form>
						<h3>Categories</h3>
						<div class="blog-categories">
							<ul>
								{% for category in categories %}
								<li><a href="{% url 'blog:categories' category.slug %}"><span>{{category}}</span></a></li>
								{% endfor %}
							</ul>
						</div>
						<h3>Recent Post</h3>
						<div class="post-box-blog">
							<div class="recent-post-box">
								{% for blog in recents %}
								<a href="{% url 'blog:blogdetail' blog.id %}">
								<div class="recent-box-blog">
									<div class="recent-img">
										<img class="img-fluid" style="height: 70px;width: 70px;" src="{{blog.image.url}}" alt="">
									</div>
									<div class="recent-info">
										<ul>
											<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author.first_name}} {{blog.author.last_name}}</span></li>
											<br>
											<li><i class="zmdi zmdi-time"></i>created at : <span>{{blog.created|date:"b d"}}</span></li>
										</ul>
										<h4>{{blog.description}}</h4>
									</div>
								</div>
									</a>
								{% endfor %}
							</div>
						</div>
						<h3>Recent Tag</h3>
						<div class="blog-tag-box">
							<ul class="list-inline tag-list">
								{% for tag in tags %}
								<li class="list-inline-item"><a href="{% url 'blog:tags' tag.slug %}">{{tag}}</a></li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endblock content %}
	<!-- End details -->
	

templates/blog/blog.html
{% extends 'base.html' %}
{% block blog-active %}active{% endblock blog-active %}
{% load static %}
{% block content %}
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>Blog</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
					</div>
				</div>
			</div>
			<div class="row">
				{% for blog in blogs %}
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" style="height: 430px;" src="{{blog.image.url}}" alt="">
						</div>
						<div class="blog-detail">
							<h4>{{blog.title}}</h4>
							<ul>
								<li><span>Post by {{blog.author}}</span></li>
								<li>|</li>
								<li><span>{{blog.created|date:"Y b d"}}</span></li>
							</ul>
							<p>{{blog.content|truncatewords:45|safe}}</p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:blogdetail' blog.id %}">Read More</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	{% if blogs.has_other_pages %}
	<div class="container mb-5">
		<div class="row">
			<div class="col d-flex justify-content-center">
				<nav aria-label="Page navigation example">
					<ul class="pagination">
						{% if blogs.has_previous %}
					  <li class="page-item"><a class="page-link" href="?page={{blogs.previous_page_number}}">Previous</a></li>
						{% endif %}
					  
						{% for page in blogs.paginator.page_range %}
						
						{% if blogs.number == page %}
						<li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
						{% else %}
						<li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
						{% endif %}
						{% endfor %}

					  {% if blogs.has_next %}
					  <li class="page-item"><a class="page-link" href="?page={{blogs.next_page_number}}">Next</a></li>
					  {% endif %}
					</ul>
				  </nav>
			</div>
		</div>
	</div>
	{% endif %}

	{% endblock content %}
	<!-- End blog -->
	